apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: local-registry:5002/ballot:latest
        ports:
        - containerPort: 8080
